### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by FlashPoint007** [simplehx/ImNext#1]
作者大大您好，在使用您的项目时，我遇到了一个问题，请问您的Foursquare数据集是经过特殊处理的嘛，我在原始数据集中找不到您在论文中使用的Foursquare数据集，请问您能提供您在项目中使用的经过处理的Foursquare原始数据集嘛？不胜感激。

**Comment by simplehx** [comment]
> 作者大大您好，在使用您的项目时，我遇到了一个问题，请问您的Foursquare数据集是经过特殊处理的嘛，我在原始数据集中找不到您在论文中使用的Foursquare数据集，请问您能提供您在项目中使用的经过处理的Foursquare原始数据集嘛？不胜感激。

您好，foursquare是下边这个链接中第五个带有好友关系的数据集。所有的数据处理步骤都在论文中注明了，如果有什么问题您可以随时提交issue或者email联系我。

https://sites.google.com/site/yangdingqi/home/foursquare-dataset

**Comment by FlashPoint007** [comment]
作者大大您好，我按照您的要求下载了对应的数据集，您在论文中使用的Foursquare数据集是不是由下面的三个文件（raw_POIs.txt、dataset_WWW_friendship_new.txt、dataset_WWW_Checkins_anonymized.txt）合成得到的签到数据集和friend数据集？因为我在您的论文中看到您使用的字段和Foursquare官方原始数据集的字段不太一样，看起来需要后期处理，而且看到您是用的US字段的数据集，我就想确认一下您是不是对Foursquare数据集的进行了一些处理，但没有体现在您的代码中，方便的话能提供一下您处理Foursquare数据集字段的代码文件嘛？不胜感激。另外，我已经跑通了您的另一个数据集Gowalla，但我在Foursquare数据集遇到了麻烦。

![image](https://github.com/simplehx/ImNext/assets/48714656/e98488de-c9ca-412b-84d4-6c6cf3b986ba)

**Comment by simplehx** [comment]
> 作者大大您好，我按照您的要求下载了对应的数据集，您在论文中使用的Foursquare数据集是不是由下面的三个文件（raw_POIs.txt、dataset_WWW_friendship_new.txt、dataset_WWW_Checkins_anonymized.txt）合成得到的签到数据集和friend数据集？因为我在您的论文中看到您使用的字段和Foursquare官方原始数据集的字段不太一样，看起来需要后期处理，而且看到您是用的US字段的数据集，我就想确认一下您是不是对Foursquare数据集的进行了一些处理，但没有体现在您的代码中，方便的话能提供一下您处理Foursquare数据集字段的代码文件嘛？不胜感激。另外，我已经跑通了您的另一个数据集Gowalla，但我在Foursquare数据集遇到了麻烦。
> 
> ![image](https://private-user-images.githubusercontent.com/48714656/325968235-e98488de-c9ca-412b-84d4-6c6cf3b986ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzM3ODYsIm5iZiI6MTcxNDEzMzQ4NiwicGF0aCI6Ii80ODcxNDY1Ni8zMjU5NjgyMzUtZTk4NDg4ZGUtYzljYS00MTJiLTg0ZDQtNmM2Y2YzYjk4NmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDEyMTEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiN2Q4OTFjOGQ3N2ExYzM1ZTZiMThjZjNmYmZiYjI2NTJhNGViODIxZGNiYzFmMmUwNDczYzRkYjhjZmM2YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y3qXuSJXzZE6sfvgCXGpr51dmDhLSFHkJj40exLk6BA)

您好，您的问题我已经清楚了，我今天没在电脑前。周末我抽时间确认一下给您回复。foursquare原始数据中有一个字段标注了国家代码，如果您是用pandas读取的，可以指定一下这个字段等于US筛选一下。具体情况我周末确认一下给您回复哈。

**Comment by FlashPoint007** [comment]
作者大大，不胜感激，我会先尝试一下处理Foursquare数据集，但我同样期待您的回复，再次感谢。

**Comment by simplehx** [comment]
> 作者大大，不胜感激，我会先尝试一下处理Foursquare数据集，但我同样期待您的回复，再次感谢。

您好，我们在前期数据处理中进行了很多的尝试，所以代码分散在多台电脑中，我尝试梳理了一下代码回答您的疑问。

1、筛选US的POI：raw_POIs.txt中存储的是POI的信息，例如经纬度，类别和国家代码。我们使用pandas读取数据，并根据country这个字段进行筛选。
```python
df = pd.read_table("./raw_POIs.txt", header=None, names=["poi", "lat", "lng", "category", "country"])
us_df = df[df["country"] == "US"]
```
如果您的实验/应用需要使用全部数据进行训练，可以忽略这一行。
```python
us_df = df[df["country"] == "US"]
```

2、将foursquare数据集转换为我们需要的格式。foursquare数据集中checkin数据存储在dataset_WWW_Checkins_anonymized.txt文件中，我们读取所有的checkin数据，并筛选出US的签到记录。
```python
all_poi = np.unique(us_df["poi"]).tolist()
df = pd.read_table("./dataset_WWW_Checkins_anonymized.txt", header=None, names=["user", "poi", "dt", "dt_offset"])
us_filter_df = df[df["poi"].isin(all_poi)]
```

因为foursquare数据集中使用的是utc时间+偏移量存储，所以我们将其转换为了本地时间。
```python
abbr2month = {abbr: index for index, abbr in enumerate(list(calendar.month_abbr))}
dt_str_list = []
for dt, dt_offset in tqdm(us_filter_df[["dt", "dt_offset"]].values):
    weekofday, month, day, time, _, year = dt.split(" ")
    month = str(abbr2month[month])
    utc_dt_str = year + "-" + month + "-" + day + " " + time
    local_dt_str = str(datetime.datetime.strptime(utc_dt_str, "%Y-%m-%d %H:%M:%S") + datetime.timedelta(minutes=dt_offset))
    dt_str_list.append(local_dt_str)
us_filter_df["dt"] = dt_str_list
```


3、处理好友关系：好友关系我们使用的是dataset_WWW_friendship_new.txt文件，我们使用pandas进行读取。
```python
df = pd.read_table("./dataset_WWW_friendship_new.txt", header=None, names=["from", "to"])
```

希望可以解答您的疑问，如果有什么问题欢迎您随时联系我。

**Comment by FlashPoint007** [comment]
> > 作者大大，不胜感激，我会先尝试一下处理Foursquare数据集，但我同样期待您的回复，再次感谢。
> 
> 您好，我们在前期数据处理中进行了很多的尝试，所以代码分散在多台电脑中，我尝试梳理了一下代码回答您的疑问。
> 
> 1、筛选US的POI：raw_POIs.txt中存储的是POI的信息，例如经纬度，类别和国家代码。我们使用pandas读取数据，并根据country这个字段进行筛选。
> 
> ```python
> df = pd.read_table("./raw_POIs.txt", header=None, names=["poi", "lat", "lng", "category", "country"])
> us_df = df[df["country"] == "US"]
> ```
> 
> 如果您的实验/应用需要使用全部数据进行训练，可以忽略这一行。
> 
> ```python
> us_df = df[df["country"] == "US"]
> ```
> 
> 2、将foursquare数据集转换为我们需要的格式。foursquare数据集中checkin数据存储在dataset_WWW_Checkins_anonymized.txt文件中，我们读取所有的checkin数据，并筛选出US的签到记录。
> 
> ```python
> all_poi = np.unique(us_df["poi"]).tolist()
> df = pd.read_table("./dataset_WWW_Checkins_anonymized.txt", header=None, names=["user", "poi", "dt", "dt_offset"])
> us_filter_df = df[df["poi"].isin(all_poi)]
> ```
> 
> 因为foursquare数据集中使用的是utc时间+偏移量存储，所以我们将其转换为了本地时间。
> 
> ```python
> abbr2month = {abbr: index for index, abbr in enumerate(list(calendar.month_abbr))}
> dt_str_list = []
> for dt, dt_offset in tqdm(us_filter_df[["dt", "dt_offset"]].values):
>     weekofday, month, day, time, _, year = dt.split(" ")
>     month = str(abbr2month[month])
>     utc_dt_str = year + "-" + month + "-" + day + " " + time
>     local_dt_str = str(datetime.datetime.strptime(utc_dt_str, "%Y-%m-%d %H:%M:%S") + datetime.timedelta(minutes=dt_offset))
>     dt_str_list.append(local_dt_str)
> us_filter_df["dt"] = dt_str_list
> ```
> 
> 3、处理好友关系：好友关系我们使用的是dataset_WWW_friendship_new.txt文件，我们使用pandas进行读取。
> 
> ```python
> df = pd.read_table("./dataset_WWW_friendship_new.txt", header=None, names=["from", "to"])
> ```
> 
> 希望可以解答您的疑问，如果有什么问题欢迎您随时联系我。

感谢作者大大的解答，我会按照您的思路来处理数据集的，再次感谢您耐心的回复。
